# Generated by Django 3.2.25 on 2025-03-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='berth_allocation',
            field=models.CharField(blank=True, choices=[('lower', 'Lower'), ('side-lower', 'Side-Lower'), ('upper', 'Upper'), ('side-upper', 'Side-Upper')], help_text='Berth allocated to this ticket', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('canceled', 'Cancelled')], default='booked', help_text='Current status of the ticket', max_length=20),
        ),
    ]
